server:
  port: 8082
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 设置允许的域名
            allowedOrigins:
              - "*"
            # 允许所有头信息
            allowedHeaders: "*"
            # 设置允许携带cookie
            # 为true时allowedOrigins不允许为* 会报错
            allowCredentials: false
            # 允许跨域请求的请求方式
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gateway
          uri: localhost:${server.port}
          predicates:
            - Path=/${spring.application.name}/**
        - id: iam
          uri: lb://iam
          predicates:
            - Path=/iam/**
        - id: eop
          uri: lb://eop
          predicates:
            - Path=/cop/**
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
ark:
  center:
    gateway:
      allow-list:
        - /iam/v1/login/account
        - /iam/v1/logout
        - /iam/v1/user/permission/elements
        - /iam/v1/user/permission/routes
feign:
  okhttp:
    enabled: true